<?php

namespace pfe\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CodeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeProduitRepository extends EntityRepository
{
}
