<?php

namespace pfe\FrontBundle\DataFixture\ORM;;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use pfe\FrontBundle\Entity\Users;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadUsers extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {


        $manager->getClassMetaData(get_class(new Users()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new Users();
        $item1->setType("");
        $item1->setName("");
        $item1->setEtat(0);
        $item1->setPost("");
        $item1->setUsername("admin");
        $item1->setUsernameCanonical("admin");
        $item1->setEmail("admin@admin.com");
        $item1->setEmailCanonical("admin@admin.com");
        $item1->setEnabled(1);
        $item1->setPassword("3ZEnnCSsPkLbQkOcsPc2CNG3ZxPHOi2/kgYKk2/bjE9gotXnHUTFgEW/hEJyNGEC4lmAkS/D52reIyFvd546ZQ==");
        $item1->setPlainPassword("");
        $item1->setLastLogin(new \DateTime("2015-05-28 02:01:36"));
        $item1->setConfirmationToken("");
        $item1->setPasswordRequestedAt("");
        $item1->setLocked(0);
        $item1->setExpired(0);
        $item1->setExpiresAt("");
        $item1->setRoles(unserialize('a:0:{}'));
        $item1->setCredentialsExpired(0);
        $item1->setCredentialsExpireAt("");
        $manager->persist($item1);

    
        $manager->flush();
    }

}
