security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_TEAM_LEADER:       ROLE_TEAM_LEADER
        ROLE_SUPERVISEUR:       ROLE_SUPERVISEUR
        ROLE_RESPONSABLE:       ROLE_RESPONSABLE
        ROLE_SUPER_ADMIN:       ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                default_target_path: /front/dashboard
                login_path: /
            logout:
                path: /logout
                target: /
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: [ROLE_TEAM_LEADER,ROLE_RESPONSABLE,ROLE_SUPERVISEUR,ROLE_ADMIN] }
        - { path: ^/resetting, role: [ROLE_TEAM_LEADER,ROLE_RESPONSABLE,ROLE_SUPERVISEUR,ROLE_ADMIN] }
        - { path: ^/front/, role: [ROLE_TEAM_LEADER,ROLE_RESPONSABLE,ROLE_SUPERVISEUR,ROLE_ADMIN]}