pfe_front_produit:
    resource: "@pfeFrontBundle/Resources/config/routing/codeproduit.yml"
    prefix:   /produit

pfe_front_kosu_suivi:
    path:     /kosu/suivi
    defaults: { _controller: pfeFrontBundle:Kosu:index }

pfe_front_donnees:
    resource: "@pfeFrontBundle/Resources/config/routing/donnees.yml"
    prefix:   /donnees

pfe_front_users:
    resource: "@pfeFrontBundle/Resources/config/routing/users.yml"
    prefix:   /users

pfe_front_archive:
    resource: "@pfeFrontBundle/Resources/config/routing/testresult.yml"
    prefix:   /archive

pfe_front_ligne:
    resource: "@pfeFrontBundle/Resources/config/routing/ligne.yml"
    prefix:   /ligne

pfe_front_homepage:
    path:     /dashboard
    defaults: { _controller: pfeFrontBundle:Default:index }
pfe_front_sheet:
    path:     /sheet/{id}
    defaults: { _controller: pfeFrontBundle:Sheet:sheet}
pfe_front_sheet-list:
    path:     /sheet-list
    defaults: { _controller: pfeFrontBundle:Sheet:sheetList}