pfe_front_archive:
    resource: "@pfeFrontBundle/Resources/config/routing/testresult.yml"
    prefix:   /archive

pfe_front_produit:
    resource: "@pfeFrontBundle/Resources/config/routing/codeproduit.yml"
    prefix:   /produit

pfe_front_ligne:
    resource: "@pfeFrontBundle/Resources/config/routing/ligne.yml"
    prefix:   /ligne

pfe_front_homepage:
    path:     /dashboard
    defaults: { _controller: pfeFrontBundle:Default:index }
pfe_front_sheet:
    path:     /sheet/{id}
    defaults: { _controller: pfeFrontBundle:Sheet:sheet}
pfe_front_sheet-list:
    path:     /sheet-list
    defaults: { _controller: pfeFrontBundle:Sheet:sheetList}